### ISSUE TITLE
Downloading files does not work

### ISSUE THREAD

**Issue by joshuatbrown** [roadfire/Sock#1]
Steps to reproduce:

1. Open a conversation with yourself.
2. Drag a file into Slack to upload it to yourself.
3. Click the Download button on the file.

Expected: The file is dowloaded.

Actual: Nothing happens.

**Comment by mattremmel** [comment]
I've started working on this here: https://github.com/mattremmel/Sock/tree/allow-file-downloads

Downloads will happen in Safari. Working on making them stay within the Sock window.

**Comment by mattremmel** [comment]
See: https://github.com/roadfire/Sock/pull/6

**Comment by joshuatbrown** [comment]
Fixed in #6.

**Comment by joshuatbrown** [comment]
This seems to be broken again — perhaps due to #13.

**Comment by joshuatbrown** [comment]
OK — I just found out that downloading still works for me when running from Xcode, but it's broken when I do an Archive. Closing this again.
