### ISSUE TITLE
Single Sign-On redirect to another browser and handling of `slack:` URLs

### ISSUE THREAD

**Issue by cpatterson-lilly** [roadfire/Sock#12]
Hi Josh,

Our company slack channels are behind a single-sign-on (SSO) solution. When signing in to Slack, we click a "SSO Login" button, which as of the latest version of Slack (3.3.8) now launches another browser in which the sign-on is completed, and then the browser redirects back to a `slack:` URL.

That does not currently work in Sock.

**Comment by joshuatbrown** [comment]
@cpatterson-lilly Thanks for reporting this! Does #13 fix it for you?

**Comment by cpatterson-lilly** [comment]
Nope, it opens the browser, but the displayed page fails to authenticate or something. It displays an error: "Page Expired. The page you are trying to access is no longer available."

**Comment by joshuatbrown** [comment]
@cpatterson-lilly Strange. I've talked to a few others who are building from `master` (which now has #13 merged) and are able to log in using SSO. Is Sock sending you out to your browser (Safari/Chrome/Firefox), or do you mean it's showing you the SSO page inside of Sock?

**Comment by cpatterson-lilly** [comment]
It's sending me out to the browser (Chrome, in this case. Haven't tried Safari yet.) The error page displays inside of Chrome.
